2022-08-05 14:02:20,921 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Configure stats pid to 13676
2022-08-05 14:02:20,921 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Loading settings from C:\Users\psiml8\.config\wandb\settings
2022-08-05 14:02:20,921 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Loading settings from c:\Users\psiml8\CausalWorld\scripts\wandb\settings
2022-08-05 14:02:20,921 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-08-05 14:02:20,921 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-08-05 14:02:20,922 INFO    MainThread:13676 [wandb_init.py:_log_setup():461] Logging user logs to c:\Users\psiml8\CausalWorld\scripts\wandb\run-20220805_140220-1zzdhk6a\logs\debug.log
2022-08-05 14:02:20,922 INFO    MainThread:13676 [wandb_init.py:_log_setup():462] Logging internal logs to c:\Users\psiml8\CausalWorld\scripts\wandb\run-20220805_140220-1zzdhk6a\logs\debug-internal.log
2022-08-05 14:02:20,922 INFO    MainThread:13676 [wandb_init.py:_jupyter_setup():411] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000209477D3E88>
2022-08-05 14:02:20,923 INFO    MainThread:13676 [wandb_init.py:init():495] calling init triggers
2022-08-05 14:02:20,923 INFO    MainThread:13676 [wandb_init.py:init():499] wandb.init called with sweep_config: {}
config: {}
2022-08-05 14:02:20,923 INFO    MainThread:13676 [wandb_init.py:init():548] starting backend
2022-08-05 14:02:20,923 INFO    MainThread:13676 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-08-05 14:02:20,929 INFO    MainThread:13676 [backend.py:ensure_launched():217] starting backend process...
2022-08-05 14:02:21,037 INFO    MainThread:13676 [backend.py:ensure_launched():222] started backend process with pid: 14176
2022-08-05 14:02:21,038 INFO    MainThread:13676 [wandb_init.py:init():558] backend started and connected
2022-08-05 14:02:21,130 INFO    MainThread:13676 [wandb_run.py:_label_probe_notebook():1084] probe notebook
2022-08-05 14:02:21,131 INFO    MainThread:13676 [wandb_run.py:_label_probe_notebook():1094] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-08-05 14:02:21,131 INFO    MainThread:13676 [wandb_init.py:init():634] updated telemetry
2022-08-05 14:02:21,507 INFO    MainThread:13676 [wandb_init.py:init():666] communicating run to backend with 30 second timeout
2022-08-05 14:02:23,180 INFO    MainThread:13676 [wandb_run.py:_on_init():1919] communicating current version
2022-08-05 14:02:23,230 INFO    MainThread:13676 [wandb_run.py:_on_init():1923] got version response upgrade_message: "wandb version 0.13.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-08-05 14:02:23,230 INFO    MainThread:13676 [wandb_init.py:init():700] starting run threads in backend
2022-08-05 14:02:28,261 INFO    MainThread:13676 [wandb_run.py:_console_start():1893] atexit reg
2022-08-05 14:02:28,262 INFO    MainThread:13676 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.WRAP
2022-08-05 14:02:28,262 INFO    MainThread:13676 [wandb_run.py:_redirect():1803] Wrapping output streams.
2022-08-05 14:02:28,265 INFO    MainThread:13676 [wandb_run.py:_redirect():1827] Redirects installed.
2022-08-05 14:02:28,265 INFO    MainThread:13676 [wandb_init.py:init():732] run started, returning control to user process
2022-08-05 14:02:28,265 INFO    MainThread:13676 [wandb_config.py:__setitem__():150] config set batch_size = 256 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002094776E888>>
2022-08-05 14:02:28,266 INFO    MainThread:13676 [wandb_run.py:_config_callback():1131] config_cb batch_size 256 None
2022-08-05 14:02:30,040 INFO    MainThread:13676 [wandb_watch.py:watch():47] Watching
2022-08-05 14:02:30,041 ERROR   MainThread:13676 [util.py:get_module():305] Error importing optional module torch
Traceback (most recent call last):
  File "c:\Users\psiml8\Anaconda3\envs\causal_world\lib\site-packages\wandb\util.py", line 300, in get_module
    return import_module(name)
  File "c:\Users\psiml8\Anaconda3\envs\causal_world\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'torch'
2022-08-05 14:02:30,718 INFO    MainThread:13676 [wandb_init.py:_pause_backend():374] pausing backend
2022-08-05 14:02:30,719 INFO    MainThread:13676 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-08-05 14:05:31,203 INFO    MainThread:13676 [wandb_init.py:_resume_backend():383] resuming backend
2022-08-05 14:05:31,235 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Configure stats pid to 13676
2022-08-05 14:05:31,235 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Loading settings from C:\Users\psiml8\.config\wandb\settings
2022-08-05 14:05:31,235 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Loading settings from c:\Users\psiml8\CausalWorld\scripts\wandb\settings
2022-08-05 14:05:31,236 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-08-05 14:05:31,236 INFO    MainThread:13676 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-08-05 14:05:31,236 INFO    MainThread:13676 [wandb_init.py:_log_setup():461] Logging user logs to c:\Users\psiml8\CausalWorld\scripts\wandb\run-20220805_140531-24t5huif\logs\debug.log
2022-08-05 14:05:31,236 INFO    MainThread:13676 [wandb_init.py:_log_setup():462] Logging internal logs to c:\Users\psiml8\CausalWorld\scripts\wandb\run-20220805_140531-24t5huif\logs\debug-internal.log
2022-08-05 14:05:31,237 INFO    MainThread:13676 [wandb_init.py:init():495] calling init triggers
2022-08-05 14:05:31,237 INFO    MainThread:13676 [wandb_init.py:init():499] wandb.init called with sweep_config: {}
config: {}
2022-08-05 14:05:31,237 INFO    MainThread:13676 [wandb_init.py:init():515] re-initializing run, found existing run on stack: 1zzdhk6a
2022-08-05 14:05:31,240 INFO    MainThread:13676 [wandb_run.py:_finish():1680] finishing run natasa-jovanovic/causal-world/1zzdhk6a
2022-08-05 14:05:31,240 INFO    MainThread:13676 [jupyter.py:save_history():435] not saving jupyter history
2022-08-05 14:05:31,240 INFO    MainThread:13676 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-08-05 14:05:31,240 INFO    MainThread:13676 [wandb_init.py:_jupyter_teardown():393] cleaning up jupyter logic
2022-08-05 14:05:31,240 INFO    MainThread:13676 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-08-05 14:05:31,242 INFO    MainThread:13676 [wandb_run.py:_restore():1834] restore
2022-08-05 14:05:31,412 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 759
}

2022-08-05 14:05:31,530 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 759
}

2022-08-05 14:05:31,744 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 759
}

2022-08-05 14:05:32,689 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 8428
}

2022-08-05 14:05:32,810 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 759
  total_bytes: 25318
}

2022-08-05 14:05:32,915 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21817
  total_bytes: 25318
}

2022-08-05 14:05:33,024 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 25318
  total_bytes: 25318
}

2022-08-05 14:05:33,133 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 25318
  total_bytes: 25318
}

2022-08-05 14:05:33,242 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 25318
  total_bytes: 25318
}

2022-08-05 14:05:33,356 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 25318
  total_bytes: 25318
}

2022-08-05 14:05:33,467 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 25318
  total_bytes: 25318
}

2022-08-05 14:05:34,059 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 25318
  total_bytes: 25318
}

2022-08-05 14:05:34,471 INFO    MainThread:13676 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 25318
  total_bytes: 25318
}
local_info {
}

2022-08-05 14:05:35,735 INFO    MainThread:13676 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-05 14:05:35,735 INFO    MainThread:13676 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-05 14:05:35,739 INFO    MainThread:13676 [wandb_run.py:_footer_sync_info():3055] logging synced files
